name: Build

on:
  push:
  pull_request:

permissions: read-all

jobs:
  build:
    name: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.4"

      - name: Install dependencies
        run: opam install . --deps-only

      - name: Build
        run: opam exec -- dune build
